### ISSUE TITLE
Cyclone Detection link broken - can I fix it ?

### ISSUE THREAD

**Issue by sajjadrahman56** [abhisheks008/DL-Simplified#939] opened 2024-10-21 14:35 UTC
The link of _**Cyclone Detection readme.md**_ file is broken 

![image](https://github.com/user-attachments/assets/d9be3569-9b95-4fd0-a628-f5a6b411f0cd)

**Comment by abhisheks008** [comment] 2024-10-24 10:54
You can fix it. But I can't put any labels for this kind of contribution.

**Comment by abhisheks008** [comment] 2024-10-24 10:56
Quick update: The issue is resolved. Hence closing this issue.

**Closed by abhisheks008** 2024-10-24 10:56 UTC
